# Total size of the memory array (RAM)
mars.ram_size=8000

# Maximum number of execution cycles before a draw is declared
mars.max_loops=80000

# Execution speed in milliseconds
gui.timer_speed=1

# Genetic algorithm parameters
genetic.population_size=20
genetic.code_size=10
genetic.generations=20
genetic.mutation_rate=0.10

# Simulated Annealing Parameters
sa.temperature=8000.0
sa.min_temperature=0.1
sa.cooling_rate=0.001