package corewar.mars.gui;

import corewar.mars.*;
import corewar.util.*;

import corewar.redcode.exceptions.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 * The bottom control panel of the MARS GUI.
 * This class is the view for the controls and the controller.
 * It contains the Redcode text area for both warriors, the buttons play and stop,
 * and manages the execution timer that drives the simulation.
 */
public class SecondPanel extends JPanel implements ActionListener{

    private WarriorEditorPanel panelW1;
    private WarriorEditorPanel panelW2;
    private JButton play;
    private JButton stop;
    private Mars mars;
    private Timer timer;

    /**
     * Constructs the control panel, initializes the sub-components (editors and buttons),
     * and sets up the timer.
     * * @param mars The mars.
     */
    public SecondPanel(Mars mars){
        super();

        this.setPreferredSize(new Dimension(800, 150));
        this.setLayout(new BorderLayout());

        JPanel editorsPanel = new JPanel(new GridLayout(1, 2));
        this.panelW1 = new WarriorEditorPanel();
        this.panelW2 = new WarriorEditorPanel();
        editorsPanel.add(this.panelW1);
        editorsPanel.add(this.panelW2);

        JPanel buttonPanel = new JPanel(new GridLayout(2, 1));
        this.play = new JButton("Play");
        this.stop = new JButton("Stop");
        buttonPanel.add(play);
        buttonPanel.add(stop);
    
        this.add(editorsPanel, BorderLayout.CENTER);
        this.add(buttonPanel, BorderLayout.EAST);

        this.play.addActionListener(this);
        this.stop.addActionListener(this);

        this.mars = mars;

        this.timer = new Timer(Config.getTimerSpeed(), e -> {
            int res = mars.step();
            if (res != -1) { 
                timer.stop();
            if (res == 0) {
                JOptionPane.showMessageDialog(this, "Draw ! Time Limit reached.");
            } else if (res == 1) {
                JOptionPane.showMessageDialog(this, "Warrior 1 won !");
            } else if (res == 2) {
                JOptionPane.showMessageDialog(this, "Warrior 2 won !");
            }
            }
        });
    }

    /**
     * Handles button click events.
     * Initiates the game load and starts the timer when "Play" is clicked,
     * or pauses the timer when "Stop" is clicked.
     * @param e The action event generated by clicking a button.
     */
    public void actionPerformed(ActionEvent e){
        Object source = e.getSource();
        if (source == this.play){
            try{
                mars.load(this.panelW1.getCode(), this.panelW2.getCode());
                 timer.start();
            }
            catch (InvalidInstructionException exception){
                JOptionPane.showMessageDialog(this, "Erreur Redcode : " + exception.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
        else if (source == this.stop){
            timer.stop();
        }
    }

}